services:
  tcbscanner:
    image: ghcr.io/deepdaddyttv/tcbscanner:latest
    container_name: tcb_scanner
    restart: unless-stopped
    ports:
      - 18080:8080
    volumes:
      - ./data:/data
      - ./manga:/manga
    environment:
      TZ: "America/New_York"
